# -*- coding: utf-8 -*-
"""Inference.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YRBfY8DLvkHO_sqtUz8px0yIYovb4Yux
"""

from peft import PeftModel
from transformers import AutoModelForCausalLM,AutoTokenizer

base_model_name="Qwen/Qwen2.5-1.5B-Instruct"
adapter_path = "/content/qwen_lora_output"

tokenizer=AutoTokenizer.from_pretrained(base_model_name)
base_model=AutoModelForCausalLM.from_pretrained(base_model_name)

model=PeftModel.from_pretrained(base_model,adapter_path)
model.eval()

messages = [
    {"role": "system", "content": "너는 민원 응답을 도와주는 assistant야."},
    {"role": "user", "content": "도로에 큰 포트홀이 생겼어요."}
]

text = tokenizer.apply_chat_template(
    messages,
    tokenize=False,
    add_generation_prompt=True
)

inputs = tokenizer(text, return_tensors="pt").to(model.device)

with torch.no_grad():
    outputs = model.generate(
        **inputs,
        max_new_tokens=128,
        do_sample=False
    )

print(tokenizer.decode(outputs[0], skip_special_tokens=True))